"""fix user column login

Revision ID: 34eac186ea1e
Revises: d37bf156d963
Create Date: 2025-09-07 21:56:25.230329

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "34eac186ea1e"
down_revision: Union[str, Sequence[str], None] = "d37bf156d963"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_t_user_login"), "t_user", ["login"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_t_user_login"), table_name="t_user")
    # ### end Alembic commands ###
